version: '2'

services:
  app:
    build: .
    command: npm start
    container_name: api-b2w
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo-b2w
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:alpine
    container_name: redis-b2w
    # command: redis-server
    ports:
      - "6379:6379"
